In [8]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

In [15]:
# generate artifical data
X = 100*np.random.rand(200, 4)+55

In [6]:
X.mean(axis=0)

array([105.15019107, 107.04622349, 104.83101486, 104.47201871])

In [7]:
X.std(axis=0)

array([29.50436286, 26.99146142, 27.14960958, 28.47922402])

In [16]:
s = StandardScaler()
X_scaled = s.fit_transform(X)

In [19]:
print(X_scaled.mean(axis=0))
print(X_scaled.std(axis=0))

[-3.73923115e-15 -1.51434421e-15 -1.72084569e-16 -1.04138920e-15]
[1. 1. 1. 1.]


In [12]:
def scale(X):
    """
    A function which inplace scales a Numpy array

    @params:
        X: numpy array with Integer or Float values
    
    @returns:
        None
    """
    means = X.mean(axis=0)
    stds = X.std(axis=0)
    for i in range(len(means)):
        X[:,i] = (X[:,i]-means[i])/stds[i]

In [13]:
# test function
X = 100*np.random.rand(200, 4)+55
scale(X)
print(X.mean(axis=0))
print(X.std(axis=0))

[2.79776202e-16 1.22124533e-17 2.38420395e-15 2.03170814e-16]
[1. 1. 1. 1.]
